services:
  - type: web
    name: smartface
    runtime: python
    buildCommand: pip install dlib-bin==20.0.1 && pip install face_recognition==1.3.0 --no-deps && pip install face-recognition-models && pip install Flask==3.0.3 psycopg2-binary==2.9.9 opencv-python-headless==4.10.0.84 numpy==1.26.4 Pillow==10.4.0 Werkzeug==3.0.3 python-dotenv==1.0.1 hypothesis==6.112.1 pytest==8.3.2 waitress==3.0.1
    startCommand: python serve.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TOLERANCE
        value: 0.45
      - key: LATE_TIME
        value: "08:00:00"
      - key: BRIGHTNESS_THRESHOLD
        value: 50
      - key: UPLOAD_DIR
        value: uploads/face_samples